#!/usr/bin/env bash
# Usage: script/gocover
# coverage test

set -e
go test ./packages/... -covermode=count -coverprofile=cover.out
go test ./packages/... -json > test-report.out
go test ./packages/... -coverprofile=coverate.out

go tool cover -func=cover.out

$HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-coverprofile
