#!/usr/bin/env bash
# Usage: script/gocover
# coverage test

set -e
go test ./package/... -covermode=count -coverprofile=cover.out
go test ./package/... -json > test-report.out
go test ./package/... -coverprofile=coverate.out

go tool cover -func=cover.out

$HOME/gopath/bin/goveralss -coverprofile=cover.out -service=travis-coverprofile
